### ISSUE TITLE
xl320_control_table.h files not included in the repo

### ISSUE THREAD

**Issue by ludusrusso** [jefesaurus/DynamixelSDK2.0#1]
Hi, I get this error when compiling:

high_level_commands.c:7:33: fatal error: xl320_control_table.h: No such file or directory

If I comment the line, compilation works fine but I cannot communicate with my xl-320.

**Comment by jefesaurus** [comment]
I just added that file. Let me know how that works. Also, I haven't implemented many of the common commands, but it should be quite easy to do so if you look within the high_level_commands.c file. This has some of the most basic ones.
